# Generated by Django 6.1.1 on 2026-09-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventory'),
        ('stores', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_products', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_products', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'external_id'), name='unique_store_external_product')],
            },
        ),
    ]
