# Generated by Django 6.1.1 on 2026-09-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_externalproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
