# Generated by Django 6.1.1 on 2026-09-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_decription_product_description'),
        ('stores', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_variants', to='stores.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_variants', to='products.variant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'external_id'), name='unique_store_external_variant')],
            },
        ),
    ]
