# Generated by Django 6.1.1 on 2026-09-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('error_type', models.CharField(max_length=100)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='synchronization.syncjob')),
            ],
        ),
    ]
