# Generated by Django 6.1.1 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('mock', 'Mock Store'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce')], max_length=50, unique=True)),
            ],
        ),
    ]
